on: [push]
name: VDET Action Test

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: LS Output
        run: ls -R
      - name: Checkout this repo code
        uses: actions/checkout@v3
      - name: Checkout VDET-Action-test
        uses: actions/checkout@v3
        with:
          repository: andrenax/VDET-Action-test
          token: ${{ secrets.PAT }}          
          path: ./.github/actions/VDET-Action-test
      - name: LS Output after checkout
        run: ls -R
      - name: VDET test
        uses: ./.github/actions/VDET-Action-test/action.yaml
      - name: LS Output after VDET test
        run: ls -R