on: [push]
name: VDET Action Test

jobs:
  first_job:
    runs-on: ubuntu-latest

    permissions:
      # only required for workflows in private repositories
      actions: read
      contents: read

      # required
      security-events: write

    steps:
      - name: Checkout this repo code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Process files changed in the current commit
        id: diff
        run: |
          changedFiles=$(git diff --name-only HEAD^)
          echo "files=${changedFiles//$'\n'/ }" >> "$GITHUB_OUTPUT"

      - name: Run VDET
        uses: andrenasx/VDET-Action-test@main
        with:
          files: ${{ steps.diff.outputs.files }}

      - name: Upload VDET report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: my-analysis-tool