on: [push]
name: VDET Action Test

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout this repo code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git checkout HEAD^
      - name: LS Output after checkout
        run: |
          pwd
          ls -R