on: [push]
name: VDET Action Test

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout this repo code
        uses: actions/checkout@v3
      - name: Run VDET
        uses: andrenasx/VDET-Action-test@main
      - name: Upload VDET results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: my-analysis-tool