on: [push]
name: VDET Action Test

jobs:
  first_job:
    runs-on: ubuntu-latest

    permissions:
      # only required for workflows in private repositories
      actions: read
      contents: read

      # required
      security-events: write

    steps:
      - name: Checkout this repo code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run VDET
        uses: andrenasx/VDET-Action-test@v1
        with:
          path: 'src/simplejavacalculator src/simplejavacalculatorTest'
          files: 'src/simplejavacalculator/Calculator.java src/simplejavacalculatorTest/CalculatorTest.java'