on: [push]
name: VDET Action Test

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: LS Output
        run: ls -a
      - name: Checkout code
        uses: actions/checkout@v3
      - name: LS Output after checkout
        run: ls -a
      - name: VDET test
        uses: andrenax/VDET-Action-test
      - name: LS Output after VDET test
        run: ls -a