on: [push]
name: VDET Action Test

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: LS Output
        run: ls -R
      - name: Checkout this repo code
        uses: actions/checkout@v3
      - name: LS Output after checkout
        run: |
          pwd
          ls -R
      - name: Run VDET
        uses: andrenasx/VDET-Action-test@v1
      - name: LS Output after VDET
        run: ls -R